export enum TranscriptionLanguage {
  Arabic = 'ar',
  Bashkir = 'ba',
  Basque = 'eu',
  Belarusian = 'be',
  Bengali = 'bn',
  Bulgarian = 'bg',
  Cantonese = 'yue',
  Catalan = 'ca',
  Croatian = 'hr',
  Czech = 'cs',
  Danish = 'da',
  Dutch = 'nl',
  English = 'en',
  Esperanto = 'eo',
  Estonian = 'et',
  Finnish = 'fi',
  French = 'fr',
  Galician = 'gl',
  German = 'de',
  Greek = 'el',
  Hebrew = 'he',
  Hindi = 'hi',
  Hungarian = 'hu',
  Indonesian = 'id',
  Interlingua = 'ia',
  Irish = 'ga',
  Italian = 'it',
  Japanese = 'ja',
  Korean = 'ko',
  Latvian = 'lv',
  Lithuanian = 'lt',
  Malay = 'ms',
  MalayEnglishBilingual = 'en_ms',
  Maltese = 'mt',
  Mandarin = 'cmn',
  MandarinEnglishBilingual = 'cmn_en',
  Marathi = 'mr',
  Mongolian = 'mn',
  Norwegian = 'no',
  Persian = 'fa',
  Polish = 'pl',
  Portuguese = 'pt',
  Romanian = 'ro',
  Russian = 'ru',
  Slovakian = 'sk',
  Slovenian = 'sl',
  Spanish = 'es',
  SpanishEnglishBilingual = 'es:bilingual-en',
  Swahili = 'sw',
  Swedish = 'sv',
  Tamil = 'ta',
  TamilEnglishBilingual = 'en_ta',
  Thai = 'th',
  Turkish = 'tr',
  Ukrainian = 'uk',
  Uyghur = 'ug',
  Urdu = 'ur',
  Vietnamese = 'vi',
  Welsh = 'cy',
}

const transcriptionLanguageMap: Record<TranscriptionLanguage, string> = {
  [TranscriptionLanguage.Arabic]: 'Arabic',
  [TranscriptionLanguage.Bashkir]: 'Bashkir',
  [TranscriptionLanguage.Basque]: 'Basque',
  [TranscriptionLanguage.Belarusian]: 'Belarusian',
  [TranscriptionLanguage.Bengali]: 'Bengali',
  [TranscriptionLanguage.Bulgarian]: 'Bulgarian',
  [TranscriptionLanguage.Cantonese]: 'Cantonese',
  [TranscriptionLanguage.Catalan]: 'Catalan',
  [TranscriptionLanguage.Croatian]: 'Croatian',
  [TranscriptionLanguage.Czech]: 'Czech',
  [TranscriptionLanguage.Danish]: 'Danish',
  [TranscriptionLanguage.Dutch]: 'Dutch',
  [TranscriptionLanguage.English]: 'English',
  [TranscriptionLanguage.Esperanto]: 'Esperanto',
  [TranscriptionLanguage.Estonian]: 'Estonian',
  [TranscriptionLanguage.Finnish]: 'Finnish',
  [TranscriptionLanguage.French]: 'French',
  [TranscriptionLanguage.Galician]: 'Galician',
  [TranscriptionLanguage.German]: 'German',
  [TranscriptionLanguage.Greek]: 'Greek',
  [TranscriptionLanguage.Hebrew]: 'Hebrew',
  [TranscriptionLanguage.Hindi]: 'Hindi',
  [TranscriptionLanguage.Hungarian]: 'Hungarian',
  [TranscriptionLanguage.Indonesian]: 'Indonesian',
  [TranscriptionLanguage.Interlingua]: 'Interlingua',
  [TranscriptionLanguage.Irish]: 'Irish',
  [TranscriptionLanguage.Italian]: 'Italian',
  [TranscriptionLanguage.Japanese]: 'Japanese',
  [TranscriptionLanguage.Korean]: 'Korean',
  [TranscriptionLanguage.Latvian]: 'Latvian',
  [TranscriptionLanguage.Lithuanian]: 'Lithuanian',
  [TranscriptionLanguage.Malay]: 'Malay',
  [TranscriptionLanguage.MalayEnglishBilingual]: 'Malay & English',
  [TranscriptionLanguage.Maltese]: 'Maltese',
  [TranscriptionLanguage.Mandarin]: 'Mandarin',
  [TranscriptionLanguage.MandarinEnglishBilingual]: 'Mandarin & English',
  [TranscriptionLanguage.Marathi]: 'Marathi',
  [TranscriptionLanguage.Mongolian]: 'Mongolian',
  [TranscriptionLanguage.Norwegian]: 'Norwegian',
  [TranscriptionLanguage.Persian]: 'Persian',
  [TranscriptionLanguage.Polish]: 'Polish',
  [TranscriptionLanguage.Portuguese]: 'Portuguese',
  [TranscriptionLanguage.Romanian]: 'Romanian',
  [TranscriptionLanguage.Russian]: 'Russian',
  [TranscriptionLanguage.Slovakian]: 'Slovakian',
  [TranscriptionLanguage.Slovenian]: 'Slovenian',
  [TranscriptionLanguage.Spanish]: 'Spanish',
  [TranscriptionLanguage.SpanishEnglishBilingual]: 'Spanish & English',
  [TranscriptionLanguage.Swahili]: 'Swahili',
  [TranscriptionLanguage.Swedish]: 'Swedish',
  [TranscriptionLanguage.Tamil]: 'Tamil',
  [TranscriptionLanguage.TamilEnglishBilingual]: 'Tamil & English',
  [TranscriptionLanguage.Thai]: 'Thai',
  [TranscriptionLanguage.Turkish]: 'Turkish',
  [TranscriptionLanguage.Ukrainian]: 'Ukrainian',
  [TranscriptionLanguage.Uyghur]: 'Uyghur',
  [TranscriptionLanguage.Urdu]: 'Urdu',
  [TranscriptionLanguage.Vietnamese]: 'Vietnamese',
  [TranscriptionLanguage.Welsh]: 'Welsh',
};

export default transcriptionLanguageMap;
