name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup CodeSignTool permissions
        run: chmod +x CodeSignTool/CodeSignTool.sh

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          # The APPLE_* values are used for auto updates signing
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # Windows code signing credentials
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
          # This token should have access to the release repository
          GH_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --mac --win

      - name: Publish draft release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
        run: |
          # Get the latest draft release and publish it
          RELEASE_ID=$(gh api repos/clozerai/clozerai-desktop-releases/releases --jq '.[] | select(.draft == true) | .id' | head -1)
          if [ -n "$RELEASE_ID" ]; then
            # First, publish the draft (remove draft status)
            gh api \
              --method PATCH \
              -H "Accept: application/vnd.github+json" \
              repos/clozerai/clozerai-desktop-releases/releases/$RELEASE_ID \
              -f draft=false
            echo "Published release $RELEASE_ID"
            
            # Then, set it as the latest release (separate API call)
            gh api \
              --method PATCH \
              -H "Accept: application/vnd.github+json" \
              repos/clozerai/clozerai-desktop-releases/releases/$RELEASE_ID \
              -f make_latest=true
            echo "Set release $RELEASE_ID as latest"
          else
            echo "No draft release found"
          fi
